{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "2abd198d-1664-41cd-a5bb-d13072f721aa",
   "metadata": {},
   "source": [
    "# Module 1: Data Profiling & Quality"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "db3c27fd-9666-4299-8f03-4d5379407148",
   "metadata": {},
   "source": [
    "### Q1. Create a complete Data Quality Report showing data type, null count, null percentage, distinct count, duplicate count, and min/max values where applicable.\n",
    "\n",
    "- Objective: \n",
    "Solve the following advanced-level Python Pandas and Data Analytics exercises using the Telecom Customer Churn dataset."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6efdeda6-44bf-4fbe-9dd6-b94d2355578a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(7043, 21)"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv(\"/Users/andreams/capstone_project/datasets/telecom_customers_churn.csv\")\n",
    "\n",
    "df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "70ecd328-6df6-4e36-84c1-ec9b58a93868",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>data_type</th>\n",
       "      <th>null_count</th>\n",
       "      <th>null_percentage</th>\n",
       "      <th>distinct_count</th>\n",
       "      <th>duplicate_count_rows</th>\n",
       "      <th>duplicate_value_count</th>\n",
       "      <th>min_value</th>\n",
       "      <th>max_value</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>customerID</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>7043</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>gender</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>7041</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>SeniorCitizen</th>\n",
       "      <td>int64</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>7041</td>\n",
       "      <td>0.00</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Partner</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>7041</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Dependents</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>7041</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>tenure</th>\n",
       "      <td>int64</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>73</td>\n",
       "      <td>0</td>\n",
       "      <td>6970</td>\n",
       "      <td>0.00</td>\n",
       "      <td>72.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>PhoneService</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>7041</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>MultipleLines</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>7040</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>InternetService</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>7040</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>OnlineSecurity</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>7040</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>OnlineBackup</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>7040</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>DeviceProtection</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>7040</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>TechSupport</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>7040</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>StreamingTV</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>7040</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>StreamingMovies</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>7040</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Contract</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>7040</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>PaperlessBilling</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>7041</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>PaymentMethod</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>7039</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>MonthlyCharges</th>\n",
       "      <td>float64</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1585</td>\n",
       "      <td>0</td>\n",
       "      <td>5458</td>\n",
       "      <td>18.25</td>\n",
       "      <td>118.75</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>TotalCharges</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6531</td>\n",
       "      <td>0</td>\n",
       "      <td>512</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Churn</th>\n",
       "      <td>object</td>\n",
       "      <td>0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>7041</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 data_type  null_count  null_percentage  distinct_count  \\\n",
       "customerID          object           0              0.0            7043   \n",
       "gender              object           0              0.0               2   \n",
       "SeniorCitizen        int64           0              0.0               2   \n",
       "Partner             object           0              0.0               2   \n",
       "Dependents          object           0              0.0               2   \n",
       "tenure               int64           0              0.0              73   \n",
       "PhoneService        object           0              0.0               2   \n",
       "MultipleLines       object           0              0.0               3   \n",
       "InternetService     object           0              0.0               3   \n",
       "OnlineSecurity      object           0              0.0               3   \n",
       "OnlineBackup        object           0              0.0               3   \n",
       "DeviceProtection    object           0              0.0               3   \n",
       "TechSupport         object           0              0.0               3   \n",
       "StreamingTV         object           0              0.0               3   \n",
       "StreamingMovies     object           0              0.0               3   \n",
       "Contract            object           0              0.0               3   \n",
       "PaperlessBilling    object           0              0.0               2   \n",
       "PaymentMethod       object           0              0.0               4   \n",
       "MonthlyCharges     float64           0              0.0            1585   \n",
       "TotalCharges        object           0              0.0            6531   \n",
       "Churn               object           0              0.0               2   \n",
       "\n",
       "                  duplicate_count_rows  duplicate_value_count  min_value  \\\n",
       "customerID                           0                      0        NaN   \n",
       "gender                               0                   7041        NaN   \n",
       "SeniorCitizen                        0                   7041       0.00   \n",
       "Partner                              0                   7041        NaN   \n",
       "Dependents                           0                   7041        NaN   \n",
       "tenure                               0                   6970       0.00   \n",
       "PhoneService                         0                   7041        NaN   \n",
       "MultipleLines                        0                   7040        NaN   \n",
       "InternetService                      0                   7040        NaN   \n",
       "OnlineSecurity                       0                   7040        NaN   \n",
       "OnlineBackup                         0                   7040        NaN   \n",
       "DeviceProtection                     0                   7040        NaN   \n",
       "TechSupport                          0                   7040        NaN   \n",
       "StreamingTV                          0                   7040        NaN   \n",
       "StreamingMovies                      0                   7040        NaN   \n",
       "Contract                             0                   7040        NaN   \n",
       "PaperlessBilling                     0                   7041        NaN   \n",
       "PaymentMethod                        0                   7039        NaN   \n",
       "MonthlyCharges                       0                   5458      18.25   \n",
       "TotalCharges                         0                    512        NaN   \n",
       "Churn                                0                   7041        NaN   \n",
       "\n",
       "                  max_value  \n",
       "customerID              NaN  \n",
       "gender                  NaN  \n",
       "SeniorCitizen          1.00  \n",
       "Partner                 NaN  \n",
       "Dependents              NaN  \n",
       "tenure                72.00  \n",
       "PhoneService            NaN  \n",
       "MultipleLines           NaN  \n",
       "InternetService         NaN  \n",
       "OnlineSecurity          NaN  \n",
       "OnlineBackup            NaN  \n",
       "DeviceProtection        NaN  \n",
       "TechSupport             NaN  \n",
       "StreamingTV             NaN  \n",
       "StreamingMovies         NaN  \n",
       "Contract                NaN  \n",
       "PaperlessBilling        NaN  \n",
       "PaymentMethod           NaN  \n",
       "MonthlyCharges       118.75  \n",
       "TotalCharges            NaN  \n",
       "Churn                   NaN  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# DATA QUALITY REPORT\n",
    "\n",
    "data_quality_report = pd.DataFrame()\n",
    "\n",
    "data_quality_report[\"data_type\"] = df.dtypes\n",
    "data_quality_report[\"null_count\"] = df.isnull().sum()\n",
    "data_quality_report[\"null_percentage\"] = (df.isnull().mean() * 100).round(2)\n",
    "data_quality_report[\"distinct_count\"] = df.nunique()\n",
    "data_quality_report[\"duplicate_count_rows\"] = df.duplicated().sum()\n",
    "data_quality_report[\"duplicate_value_count\"] = df.apply(lambda x: x.duplicated().sum())\n",
    "\n",
    "data_quality_report[\"min_value\"] = df.select_dtypes(include=\"number\").min()\n",
    "data_quality_report[\"max_value\"] = df.select_dtypes(include=\"number\").max()\n",
    "\n",
    "data_quality_report"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "41e5dbb5-52f9-484f-adb5-c6aaebc80d12",
   "metadata": {},
   "source": [
    "### Q2. The TotalCharges column is stored as an object. Identify invalid values, convert it to numeric, and quantify affected records."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "81800c5e-8fcb-4af6-a5f0-2fcfa29a9b7b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "11\n"
     ]
    }
   ],
   "source": [
    "# Identify invalid values\n",
    "\n",
    "## give me the original TotalCharges values where the conversion produced NaN, but the original value was NOT already NaN.\n",
    "invalid_values = df[\"TotalCharges\"][\n",
    "    pd.to_numeric(df[\"TotalCharges\"], errors=\"coerce\").isna()\n",
    "    & df[\"TotalCharges\"].notna()\n",
    "]\n",
    "\n",
    "# quantify affected records \n",
    "invalid_count = invalid_values.count()\n",
    "\n",
    "print(invalid_count)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a70ff73c-0751-4678-904f-14c8f8282ba0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "float64\n",
      "customerID           0\n",
      "gender               0\n",
      "SeniorCitizen        0\n",
      "Partner              0\n",
      "Dependents           0\n",
      "tenure               0\n",
      "PhoneService         0\n",
      "MultipleLines        0\n",
      "InternetService      0\n",
      "OnlineSecurity       0\n",
      "OnlineBackup         0\n",
      "DeviceProtection     0\n",
      "TechSupport          0\n",
      "StreamingTV          0\n",
      "StreamingMovies      0\n",
      "Contract             0\n",
      "PaperlessBilling     0\n",
      "PaymentMethod        0\n",
      "MonthlyCharges       0\n",
      "TotalCharges        11\n",
      "Churn                0\n",
      "dtype: int64\n"
     ]
    }
   ],
   "source": [
    "# convert it to numeric\n",
    "\n",
    "df[\"TotalCharges\"] = pd.to_numeric(\n",
    "    df[\"TotalCharges\"],\n",
    "    errors=\"coerce\"\n",
    ")\n",
    "\n",
    "print(df[\"TotalCharges\"].dtype)\n",
    "print(df.isna().sum())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0c239721-c396-48be-a810-7e1dbf321af4",
   "metadata": {},
   "source": [
    "### Q3. Create a function that automatically categorizes columns into Numerical, Categorical, Binary, and Identifier groups."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "29249c4e-70ea-42b6-817d-03812d954d88",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'Numerical': ['tenure', 'MonthlyCharges', 'TotalCharges'], 'Categorical': ['MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod'], 'Binary': ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn'], 'Identifier': ['customerID']}\n"
     ]
    }
   ],
   "source": [
    "def categorize_columns(df):\n",
    "    numerical = []\n",
    "    categorical = []\n",
    "    binary = []\n",
    "    identifier = []\n",
    "\n",
    "    for column in df.columns:\n",
    "        if column.lower().endswith(\"id\"):\n",
    "            identifier.append(column)\n",
    "        elif df[column].nunique() == 2:\n",
    "            binary.append(column)\n",
    "        elif pd.api.types.is_numeric_dtype(df[column]):\n",
    "            numerical.append(column)\n",
    "        else:\n",
    "            categorical.append(column)\n",
    "    return {\n",
    "        \"Numerical\": numerical,\n",
    "        \"Categorical\": categorical,\n",
    "        \"Binary\": binary,\n",
    "        \"Identifier\": identifier\n",
    "    }\n",
    "\n",
    "categories = categorize_columns(df)\n",
    "\n",
    "print(categories)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "71979cfe-f37b-44aa-bafc-f66ab45d22cc",
   "metadata": {},
   "source": [
    "### Q4. Identify customers where TotalCharges differs from MonthlyCharges × Tenure by more than 10%. Investigate possible causes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "31e16e6d-ae85-46bb-9130-0b6c949e3ba9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of affected customers: 381\n"
     ]
    }
   ],
   "source": [
    "# expected total charges \n",
    "\n",
    "df[\"expected_total_charges\"] = df[\"MonthlyCharges\"] * df[\"tenure\"]\n",
    "\n",
    "# percentage difference \n",
    "\n",
    "df[\"difference_percentage\"] = (\n",
    "    abs(df[\"TotalCharges\"] - df[\"expected_total_charges\"])\n",
    "    / df[\"expected_total_charges\"]\n",
    ") * 100\n",
    "\n",
    "# TotalCharges differs from MonthlyCharges × Tenure by more than 10%\n",
    "\n",
    "affected_customers = df[df[\"difference_percentage\"] > 10]\n",
    "\n",
    "# affected customers\n",
    "\n",
    "affected_customers[\n",
    "    [\n",
    "        \"customerID\",\n",
    "        \"tenure\",\n",
    "        \"MonthlyCharges\",\n",
    "        \"TotalCharges\",\n",
    "        \"expected_total_charges\",\n",
    "        \"difference_percentage\"\n",
    "\n",
    "    ]\n",
    "]\n",
    "\n",
    "print(\"Number of affected customers:\", len(affected_customers))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "4ad168e7-36a7-4b27-ba35-5c214ca494e4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Affected %</th>\n",
       "      <th>All %</th>\n",
       "      <th>Difference</th>\n",
       "      <th>Column</th>\n",
       "      <th>Category</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>No internet service</th>\n",
       "      <td>50.131234</td>\n",
       "      <td>21.666903</td>\n",
       "      <td>28.464330</td>\n",
       "      <td>StreamingMovies</td>\n",
       "      <td>No internet service</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>No internet service</th>\n",
       "      <td>50.131234</td>\n",
       "      <td>21.666903</td>\n",
       "      <td>28.464330</td>\n",
       "      <td>OnlineBackup</td>\n",
       "      <td>No internet service</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>No internet service</th>\n",
       "      <td>50.131234</td>\n",
       "      <td>21.666903</td>\n",
       "      <td>28.464330</td>\n",
       "      <td>StreamingTV</td>\n",
       "      <td>No internet service</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>No internet service</th>\n",
       "      <td>50.131234</td>\n",
       "      <td>21.666903</td>\n",
       "      <td>28.464330</td>\n",
       "      <td>TechSupport</td>\n",
       "      <td>No internet service</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>No</th>\n",
       "      <td>50.131234</td>\n",
       "      <td>21.666903</td>\n",
       "      <td>28.464330</td>\n",
       "      <td>InternetService</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>No internet service</th>\n",
       "      <td>50.131234</td>\n",
       "      <td>21.666903</td>\n",
       "      <td>28.464330</td>\n",
       "      <td>DeviceProtection</td>\n",
       "      <td>No internet service</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>No internet service</th>\n",
       "      <td>50.131234</td>\n",
       "      <td>21.666903</td>\n",
       "      <td>28.464330</td>\n",
       "      <td>OnlineSecurity</td>\n",
       "      <td>No internet service</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Mailed check</th>\n",
       "      <td>44.881890</td>\n",
       "      <td>22.887974</td>\n",
       "      <td>21.993916</td>\n",
       "      <td>PaymentMethod</td>\n",
       "      <td>Mailed check</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>No</th>\n",
       "      <td>69.816273</td>\n",
       "      <td>48.132898</td>\n",
       "      <td>21.683375</td>\n",
       "      <td>MultipleLines</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Month-to-month</th>\n",
       "      <td>71.391076</td>\n",
       "      <td>55.019168</td>\n",
       "      <td>16.371908</td>\n",
       "      <td>Contract</td>\n",
       "      <td>Month-to-month</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                     Affected %      All %  Difference            Column  \\\n",
       "No internet service   50.131234  21.666903   28.464330   StreamingMovies   \n",
       "No internet service   50.131234  21.666903   28.464330      OnlineBackup   \n",
       "No internet service   50.131234  21.666903   28.464330       StreamingTV   \n",
       "No internet service   50.131234  21.666903   28.464330       TechSupport   \n",
       "No                    50.131234  21.666903   28.464330   InternetService   \n",
       "No internet service   50.131234  21.666903   28.464330  DeviceProtection   \n",
       "No internet service   50.131234  21.666903   28.464330    OnlineSecurity   \n",
       "Mailed check          44.881890  22.887974   21.993916     PaymentMethod   \n",
       "No                    69.816273  48.132898   21.683375     MultipleLines   \n",
       "Month-to-month        71.391076  55.019168   16.371908          Contract   \n",
       "\n",
       "                                Category  \n",
       "No internet service  No internet service  \n",
       "No internet service  No internet service  \n",
       "No internet service  No internet service  \n",
       "No internet service  No internet service  \n",
       "No                                    No  \n",
       "No internet service  No internet service  \n",
       "No internet service  No internet service  \n",
       "Mailed check                Mailed check  \n",
       "No                                    No  \n",
       "Month-to-month            Month-to-month  "
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "### overview of comparison the characteristics of affected customers with all customers\n",
    "\n",
    "possible_causes = []\n",
    "\n",
    "for column in categories[\"Categorical\"] + categories[\"Binary\"]:\n",
    "    affected_pct = affected_customers[column].value_counts(normalize=True) * 100\n",
    "    all_pct = df[column].value_counts(normalize=True) * 100\n",
    "    \n",
    "    comparison = pd.DataFrame({\n",
    "        \"Affected %\": affected_pct,\n",
    "        \"All %\": all_pct\n",
    "    }).fillna(0)\n",
    "    \n",
    "    comparison[\"Difference\"] = (\n",
    "        comparison[\"Affected %\"] - comparison[\"All %\"]\n",
    "    )\n",
    "    \n",
    "    comparison[\"Column\"] = column\n",
    "    comparison[\"Category\"] = comparison.index\n",
    "    \n",
    "    possible_causes.append(comparison)\n",
    "\n",
    "possible_causes = pd.concat(possible_causes)\n",
    "\n",
    "# show the biggest overrepresented categories\n",
    "possible_causes.sort_values(\"Difference\", ascending=False).head(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "81713ee8-b7b8-4e40-afc7-25834ac94779",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead tr th {\n",
       "        text-align: left;\n",
       "    }\n",
       "\n",
       "    .dataframe thead tr:last-of-type th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr>\n",
       "      <th></th>\n",
       "      <th colspan=\"2\" halign=\"left\">tenure</th>\n",
       "      <th colspan=\"2\" halign=\"left\">MonthlyCharges</th>\n",
       "      <th colspan=\"2\" halign=\"left\">TotalCharges</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th></th>\n",
       "      <th>mean</th>\n",
       "      <th>median</th>\n",
       "      <th>mean</th>\n",
       "      <th>median</th>\n",
       "      <th>mean</th>\n",
       "      <th>median</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>difference_percentage</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>False</th>\n",
       "      <td>33.665416</td>\n",
       "      <td>31.0</td>\n",
       "      <td>66.213389</td>\n",
       "      <td>71.925</td>\n",
       "      <td>2396.583288</td>\n",
       "      <td>1532.45</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>True</th>\n",
       "      <td>9.740157</td>\n",
       "      <td>6.0</td>\n",
       "      <td>39.377953</td>\n",
       "      <td>25.100</td>\n",
       "      <td>305.756562</td>\n",
       "      <td>218.55</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                          tenure        MonthlyCharges         TotalCharges  \\\n",
       "                            mean median           mean  median         mean   \n",
       "difference_percentage                                                         \n",
       "False                  33.665416   31.0      66.213389  71.925  2396.583288   \n",
       "True                    9.740157    6.0      39.377953  25.100   305.756562   \n",
       "\n",
       "                                \n",
       "                        median  \n",
       "difference_percentage           \n",
       "False                  1532.45  \n",
       "True                    218.55  "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# true → customers whose difference_percentage is greater than 10% → your affected customers\n",
    "# false → customers whose difference is 10% or less → non-affected customers\n",
    "\n",
    "possible_causes_numerical = df.groupby(\n",
    "    df[\"difference_percentage\"] > 10\n",
    ")[[\"tenure\", \"MonthlyCharges\", \"TotalCharges\"]].agg([\"mean\", \"median\"])\n",
    "\n",
    "possible_causes_numerical"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "abbb2600-b582-43db-a758-10fe86e06fa6",
   "metadata": {},
   "source": [
    "### Possible causes: \n",
    "\n",
    "- Customers with no internet service, mailed-check payment methods, no multiple lines, and month-to-month contracts are overrepresented among customers whose TotalCharges differs from MonthlyCharges × tenure by more than 10%. These characteristics may therefore be associated with the discrepancy.\n",
    "\n",
    "- The customers with >10% discrepancies are heavily concentrated among customers with short tenure.\n",
    "\n",
    "- The affected customers are characterized by shorter tenure and are more likely to have no internet service, use mailed checks, and have month-to-month contracts compared with the overall customer population. These characteristics may be associated with the discrepancy between TotalCharges and MonthlyCharges × tenure."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3a85e7af-81e8-41fc-a7b9-3f4f46cf05e6",
   "metadata": {},
   "source": [
    "# Module 2: Advanced Customer Analytics"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "455a7b01-8c0b-4fbc-9db3-dd3443cdef76",
   "metadata": {},
   "source": [
    "Formula churn rate: \n",
    "\n",
    "Churn Rate = Number of customers who churned / Total number of customers * 100"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2ac8790e-f634-4a57-a33c-d59b459bfc33",
   "metadata": {},
   "source": [
    "### Q6. Calculate churn rate by Gender, Senior Citizen, Partner, and Dependents. Rank the highest-risk customer groups."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "597fce84-21ed-422b-b815-a7dacc386d54",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "churn_rate_gender:\n",
      "gender\n",
      "Female    26.920872\n",
      "Male      26.160338\n",
      "Name: Churn, dtype: float64\n",
      "\n",
      "churn_rate_senior:\n",
      "SeniorCitizen\n",
      "No     23.606168\n",
      "Yes    41.681261\n",
      "Name: Churn, dtype: float64\n",
      "\n",
      "churn_rate_partner:\n",
      "Partner\n",
      "No     32.957979\n",
      "Yes    19.664903\n",
      "Name: Churn, dtype: float64\n",
      "\n",
      "churn_rate_dependents:\n",
      "Dependents\n",
      "No     31.279140\n",
      "Yes    15.450237\n",
      "Name: Churn, dtype: float64\n"
     ]
    }
   ],
   "source": [
    "### churn_rate_gender\n",
    "\n",
    "churn_rate_gender = (\n",
    "    df.groupby(\"gender\")[\"Churn\"]\n",
    "      .apply(lambda x: (x == \"Yes\").mean() * 100)\n",
    ")\n",
    "\n",
    "### churn_rate_senior\n",
    "\n",
    "churn_rate_senior = (\n",
    "    df.groupby(\"SeniorCitizen\")[\"Churn\"]\n",
    "      .apply(lambda x: (x == \"Yes\").mean() * 100)\n",
    "      .rename(index={1: \"Yes\", 0: \"No\"})\n",
    ")\n",
    "\n",
    "### churn_rate_partner\n",
    "\n",
    "churn_rate_partner = (\n",
    "    df.groupby(\"Partner\")[\"Churn\"]\n",
    "      .apply(lambda x: (x == \"Yes\").mean() * 100)\n",
    ")\n",
    "### churn_rate_dependents\n",
    "\n",
    "churn_rate_dependents = (\n",
    "    df.groupby(\"Dependents\")[\"Churn\"]\n",
    "        .apply(lambda x: (x == \"Yes\").mean() * 100)\n",
    ")\n",
    "\n",
    "print(\"churn_rate_gender:\")\n",
    "print(churn_rate_gender)\n",
    "\n",
    "print(\"\\nchurn_rate_senior:\")\n",
    "print(churn_rate_senior)\n",
    "\n",
    "print(\"\\nchurn_rate_partner:\")\n",
    "print(churn_rate_partner)\n",
    "\n",
    "print(\"\\nchurn_rate_dependents:\")\n",
    "print(churn_rate_dependents)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "ad01451f-7d50-47bd-8e4b-f6fdb7366c8e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Senior Citizen  Yes       41.681261\n",
      "Partner         No        32.957979\n",
      "Dependents      No        31.279140\n",
      "Gender          Female    26.920872\n",
      "                Male      26.160338\n",
      "Senior Citizen  No        23.606168\n",
      "Partner         Yes       19.664903\n",
      "Dependents      Yes       15.450237\n",
      "Name: Churn, dtype: float64\n"
     ]
    }
   ],
   "source": [
    "## Rank the highest-risk customer groups.\n",
    "\n",
    "ranking_higher_risk_customer_groups = pd.concat([\n",
    "    churn_rate_gender,\n",
    "    churn_rate_senior,\n",
    "    churn_rate_partner,\n",
    "    churn_rate_dependents\n",
    "], keys=[\"Gender\", \"Senior Citizen\", \"Partner\", \"Dependents\"])\n",
    "\n",
    "ranking_higher_risk_customer_groups = ranking_higher_risk_customer_groups.sort_values(ascending=False)\n",
    "\n",
    "print(ranking_higher_risk_customer_groups)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d04d3604-2240-48b8-8aa1-c3292e7c3db8",
   "metadata": {},
   "source": [
    "Senior citizens are the highest-risk customer group, with a churn rate of 41.7%. Customers without a partner (33.0%) and without dependents (31.3%) also have relatively high churn rates. Gender appears to have little impact on churn, as the rates for females (26.9%) and males (26.2%) are very similar. Customers with dependents have the lowest churn rate (15.5%)."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1cbfe1a7-2c7b-44a1-a38c-8577118999d5",
   "metadata": {},
   "source": [
    "### Q7. Create customer segments based on tenure and analyze churn across segments."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "81e6624a-5b1e-4d31-9446-7831cc6dae49",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "customer_segment_tenure\n",
      "New            47.438243\n",
      "Early          28.710938\n",
      "Established    20.388959\n",
      "Long-term       9.513176\n",
      "Name: Churn, dtype: float64\n"
     ]
    }
   ],
   "source": [
    "### customer segments based on tenure\n",
    "\n",
    "def create_customer_segment_tenure(tenure):\n",
    "    if tenure <=12:\n",
    "        return \"New\"\n",
    "        \n",
    "    elif tenure <= 24:\n",
    "        return \"Early\"\n",
    "\n",
    "    elif tenure <= 48:\n",
    "        return \"Established\"\n",
    "        \n",
    "    else:\n",
    "        return \"Long-term\"\n",
    "\n",
    "df[\"customer_segment_tenure\"] = df[\"tenure\"].apply(create_customer_segment_tenure)\n",
    "\n",
    "### analyze churn across segments\n",
    "\n",
    "churn_segment = (\n",
    "    df.groupby(\"customer_segment_tenure\")[\"Churn\"]\n",
    "      .apply(lambda x: (x == \"Yes\").mean() * 100)\n",
    "      .sort_values(ascending=False)\n",
    ")\n",
    "\n",
    "print(churn_segment)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "94cfb09c-a515-4da3-9a40-0c71f602791a",
   "metadata": {},
   "source": [
    "New customers are more likely to churn"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "83af4df5-7bc5-4103-b351-973b1bbf2af2",
   "metadata": {},
   "source": [
    "### Q8. Identify the top 10 customer profiles most likely to churn using combinations of Contract, Payment Method, and Internet Service."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "id": "77f46dab-9bda-43c7-9363-c6b9c439f5b0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "          Contract              PaymentMethod InternetService  customers  \\\n",
      "7   Month-to-month           Electronic check     Fiber optic       1307   \n",
      "10  Month-to-month               Mailed check     Fiber optic        201   \n",
      "1   Month-to-month  Bank transfer (automatic)     Fiber optic        327   \n",
      "4   Month-to-month    Credit card (automatic)     Fiber optic        293   \n",
      "6   Month-to-month           Electronic check             DSL        474   \n",
      "9   Month-to-month               Mailed check             DSL        367   \n",
      "3   Month-to-month    Credit card (automatic)             DSL        185   \n",
      "19        One year           Electronic check     Fiber optic        196   \n",
      "11  Month-to-month               Mailed check              No        325   \n",
      "2   Month-to-month  Bank transfer (automatic)              No         65   \n",
      "\n",
      "    churned  churn_rate  \n",
      "7       789   60.367253  \n",
      "10      102   50.746269  \n",
      "1       149   45.565749  \n",
      "4       122   41.638225  \n",
      "6       192   40.506329  \n",
      "9       113   30.790191  \n",
      "3        50   27.027027  \n",
      "19       51   26.020408  \n",
      "11       67   20.615385  \n",
      "2        13   20.000000  \n"
     ]
    }
   ],
   "source": [
    "top_10_customers_profiles_to_churn = (\n",
    "    df.groupby([\"Contract\", \"PaymentMethod\", \"InternetService\"])[\"Churn\"]\n",
    "    .agg(\n",
    "        customers=\"size\",\n",
    "        churned=lambda x: (x == \"Yes\").sum()\n",
    "    )\n",
    "    .reset_index()\n",
    ")\n",
    "\n",
    "top_10_customers_profiles_to_churn[\"churn_rate\"] = (\n",
    "    top_10_customers_profiles_to_churn[\"churned\"]\n",
    "    / top_10_customers_profiles_to_churn[\"customers\"]\n",
    "    * 100\n",
    ")\n",
    "\n",
    "top_10_customers_profiles_to_churn = (\n",
    "    top_10_customers_profiles_to_churn\n",
    "    .sort_values(\"churn_rate\", ascending=False)\n",
    "    .head(10)\n",
    ")\n",
    "\n",
    "\n",
    "print(top_10_customers_profiles_to_churn)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "44737609-057b-4e55-9252-ef44956ceda3",
   "metadata": {},
   "source": [
    "The analysis shows that month-to-month customers have the highest churn across most customer profiles. The highest-churn profile is month-to-month customers using electronic checks and fiber optic internet, with a churn rate of 60.4% (789 out of 1,307 customers). Overall, month-to-month contracts, electronic check payment, and fiber optic internet are frequently associated with high-churn customer profiles."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d0d5aa0f-5deb-4c04-be60-01512b4254be",
   "metadata": {},
   "source": [
    "### Q9. Calculate Customer Lifetime Value (CLV = MonthlyCharges × Tenure) and compare churned vs retained customers."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "528fb148-e11b-491b-944e-3f8913a878c4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  Churn  customers  average_clv\n",
      "0    No       5174      2549.77\n",
      "1   Yes       1869      1531.61\n"
     ]
    }
   ],
   "source": [
    "# customer lifetime value calculation\n",
    "\n",
    "df[\"CLV\"] = df[\"MonthlyCharges\"] * df[\"tenure\"]\n",
    "\n",
    "\n",
    "## churned vs retained customers\n",
    "clv_churn_vs_retained = (\n",
    "    df.groupby(\"Churn\")\n",
    "    .agg(\n",
    "        customers=(\"CLV\", \"size\"),\n",
    "        average_clv=(\"CLV\", \"mean\")\n",
    "    )\n",
    "    .reset_index()\n",
    ")\n",
    "\n",
    "print(clv_churn_vs_retained.round(2))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2f952550-2429-4320-a6bb-42dfab0c6380",
   "metadata": {},
   "source": [
    "### Q10. Create a Customer Risk Score using Contract Type, Tenure, Tech Support, and Online Security."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "id": "d7df4a7e-597f-4580-97dc-07dd34b00837",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "OnlineSecurity\n",
       "No                     41.766724\n",
       "No internet service     7.404980\n",
       "Yes                    14.611194\n",
       "Name: Churn, dtype: float64"
      ]
     },
     "execution_count": 62,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "## check churn rate OnlineSecurity\n",
    "df.groupby(\"OnlineSecurity\")[\"Churn\"].apply(\n",
    "    lambda x: (x == \"Yes\").mean() * 100\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "id": "3cff391a-618d-4b7a-80ac-4c4d8bc2ce74",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "TechSupport\n",
       "No                     41.635474\n",
       "No internet service     7.404980\n",
       "Yes                    15.166341\n",
       "Name: Churn, dtype: float64"
      ]
     },
     "execution_count": 63,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "## check churn rate TechSupport\n",
    "df.groupby(\"TechSupport\")[\"Churn\"].apply(\n",
    "    lambda x: (x == \"Yes\").mean() * 100\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "id": "caa36e51-16d3-4e6f-97e1-c94b02c21b29",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Contract\n",
       "Month-to-month    42.709677\n",
       "One year          11.269518\n",
       "Two year           2.831858\n",
       "Name: Churn, dtype: float64"
      ]
     },
     "execution_count": 65,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "## check churn rate based on contract \n",
    "\n",
    "df.groupby(\"Contract\")[\"Churn\"].apply(\n",
    "    lambda x: (x == \"Yes\").mean() * 100\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "id": "a544d56d-8881-4844-a65b-18767fc1142b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "         Contract  tenure TechSupport OnlineSecurity  customer_risk_score\n",
      "0  Month-to-month       1          No             No                    4\n",
      "1        One year      34          No            Yes                    1\n",
      "2  Month-to-month       2          No            Yes                    3\n",
      "3        One year      45         Yes            Yes                    0\n",
      "4  Month-to-month       2          No             No                    4\n",
      "5  Month-to-month       8          No             No                    4\n",
      "6  Month-to-month      22          No             No                    3\n",
      "7  Month-to-month      10          No            Yes                    3\n",
      "8  Month-to-month      28         Yes             No                    2\n",
      "9        One year      62          No            Yes                    1\n"
     ]
    }
   ],
   "source": [
    "df[\"customer_risk_score\"] = (\n",
    "    (df[\"Contract\"] == \"Month-to-month\").astype(int)\n",
    "    + (df[\"tenure\"] < 12).astype(int)\n",
    "    + (df[\"TechSupport\"] == \"No\").astype(int)\n",
    "    + (df[\"OnlineSecurity\"] == \"No\").astype(int)\n",
    ")\n",
    "\n",
    "print(df[[\n",
    "    \"Contract\",\n",
    "    \"tenure\", \n",
    "    \"TechSupport\", \n",
    "    \"OnlineSecurity\", \n",
    "    \"customer_risk_score\"\n",
    "]].head(10))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
